name: Build Protected Version

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Create protected version
      run: |
        # Copy all files to dist
        cp -r public dist
        
        # Add basic protection to HTML
        sed -i 's|<head>|<head><style>body{-webkit-user-select:none;-moz-user-select:none;user-select:none}</style>|' dist/index.html
        
        # Add protection script before closing body tag
        sed -i 's|</body>|<script>document.addEventListener("contextmenu",e=>e.preventDefault());document.addEventListener("keydown",e=>{if(e.key==="F12"||e.ctrlKey&&e.shiftKey&&e.key==="I"||e.ctrlKey&&e.key==="u"){e.preventDefault();alert("🔒 Developer tools disabled");}});</script></body>|' dist/index.html
        
    - name: Deploy to protected branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b protected || git checkout protected
        
        # Remove existing files except .git
        find . -name .git -prune -o -type f -exec rm -f {} +
        
        # Copy new files
        cp -r dist/* .
        
        # Commit and push
        git add .
        git commit -m "Protected build $(date)" || echo "No changes"
        git push origin protected --force
